trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Assign_RBAC
  displayName: Assign Azure RBAC Roles
  jobs:
  - job: assign_roles
    steps:
    - task: AzureCLI@2
      displayName: 'Assign RBAC roles'
      inputs:
        azureSubscription: 'aks-sc'   # Service connection name
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
         az aks create --resource-group randomapp-rg --name aks-cluster --node-count 1 --enable-addons monitoring --generate-ssh-keysnitoring --generate-ssh-keys --attach-acr appcer