trigger: none

parameters:
  - name: nsgName
    type: string
    default: 'my-nsg'
  - name: resourceGroup
    type: string
    default: 'my-rg'

  - name: ruleName
    type: string
    default: 'Allow-Rule'
  - name: priority
    type: number
    default: 200
  - name: direction
    type: string
    default: 'Inbound'
    values:
      - Inbound
      - Outbound
  - name: protocol
    type: string
    default: 'Tcp'
  - name: port
    type: string
    default: '80'
  - name: description
    type: string
    default: 'Allow traffic'

pool:
  vmImage: ubuntu-latest

stages:
- stage: AddNSGRule
  jobs:
  - job: DeployRule
    steps:
    - task: AzureCLI@2
      displayName: 'Add NSG Rule (Dynamic Direction)'
      inputs:
        azureSubscription: 'aks-sc'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Creating NSG rule in direction: ${{ parameters.direction }}"
          
          az network nsg rule create \
            --resource-group '${{ parameters.resourceGroup }}' \
            --nsg-name '${{ parameters.nsgName }}' \
            --name '${{ parameters.ruleName }}' \
            --priority ${{ parameters.priority }} \
            --direction '${{ parameters.direction }}' \
            --access Allow \
            --protocol '${{ parameters.protocol }}' \
            --source-address-prefixes '*' \
            --source-port-ranges '*' \
            --destination-address-prefixes '*' \
            --destination-port-ranges '${{ parameters.port }}' \
            --description "${{ parameters.description }}"
