trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'python-api'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: Docker@2
  inputs:
    command: buildAndPush
    repository: appcer.azurecr.io/myapp   # This is the full ACR login server + repo name
    containerRegistry: 'acr-sc'          # Your service connection name
    dockerfile: '**/Dockerfile'
    tags: latest

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'aks-sc'
    azureResourceGroup: 'aks-cluster'
    kubernetesCluster: 'randomapp-rg'
    namespace: 'default'
    command: apply
    useConfigurationFile: true
    configuration: 'CICD/deployment.yaml'