trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'python-api'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

# - task: Docker@2
#   inputs:
#     command: buildAndPush
#     repository: appcer.azurecr.io/myapp   # This is the full ACR login server + repo name
#     containerRegistry: 'acr-sc'          # Your service connection name
#     dockerfile: '**/Dockerfile'
#     tags: latest

- task: AzureCLI@2
  displayName: 'Get AKS credentials'
  inputs:
    azureSubscription: 'aks-sc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group randomapp-rg --name aks-cluster --overwrite-existing

- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'None'
    command: apply
    useConfigurationFile: true
    configuration: 'CICD/deployment.yml'