apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-api
  labels:
    app: random-string
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      containers:
        - name: api
          image: mmtacr.azurecr.io/myapp:latest2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: random-string-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # Makes it internal
spec:
  selector:
    app: random-string
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: random-string-ingress
#   annotations:
#     # if using cert-manager:
#     # cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   ingressClassName: azure/application-gateway  # for AGIC
#   rules:
#     - http:
#         paths:
#           - path: /generate
#             pathType: Prefix
#             backend:
#               service:
#                 name: random-string-service
#                 port:
#                   number: 80
