apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-slack-alert
  namespace: monitoring
spec:
  groups:
    - name: test
      rules:
        - alert: SlackIntegrationTest
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Slack test alert"
            description: "If you see this in Slack, your Alertmanager Slack config is working."
