trigger:
   - none
 
pool:
  vmImage: ubuntu-latest
variables:
  - group: random-vars

stages:
- stage: deploy_infrastructure
  displayName : "deploy infrastructure"
  jobs:
  - job :
    steps:
        - task: AzureCLI@2
          displayName: "deploy infrastructure"
          inputs:
            azureSubscription: 'aks-sc'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
                          az deployment group create \
                          --resource-group "randomapp-rg" \
                          --mode Incremental \
                          --template-file "$(System.DefaultWorkingDirectory)/InfraProvisioning/main.bicep" \
                          --parameters virtualNetworkName="$(virtualNetworkName)" \
                                      AkssubnetName="$(AkssubnetName)" \
                                      AppgwsubnetName="$(AppgwsubnetName)" \
                                      PlesubnetName="$(PlesubnetName)" 
                            
                          