trigger:
   - none
parameters:
  - name: env
    displayName: enter the environment to deploy
    default: d
    values:
      - d
      - t
      - a
      - p

pool:
  vmImage: ubuntu-latest
variables:
  - group: random-${{parameters.env}}-vars

stages:
- stage: deploy_infrastructure
  displayName : "deploy infrastructure"
  jobs:
  - job :
    displayName: "deploy infrastructure"
    steps:
        - task: AzureCLI@2
          displayName: "Run What-If Deployment"
          inputs:
            azureSubscription: 'aks-sc1'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group what-if \
                --resource-group "mmt-aks" \
                --template-file "$(System.DefaultWorkingDirectory)/InfraProvisioning/main.bicep" \
                --parameters virtualNetworkName="$(virtualNetworkName)" \
                            AkssubnetName="$(AkssubnetName)" \
                            AppgwsubnetName="$(AppgwsubnetName)" \
                            PlesubnetName="$(PlesubnetName)" \
                            windowsAdminPassword="$(windowsAdminPassword)" \
                            acrName="$(acrName)" \
                            frontendfqdn="$(frontendfqdn)" \
                            applicationGateways_appgw_name="$(appGatewayName)" \
                            appgwkeyvault="$(appgwkeyvault)" \
                            storageAccountName="$(storageAccountName)" \
                            umiName="$(umiName)" \
                            Plesubnetid="$(plesubnetid)" \
                            appgwSubnetID="$(appgwsubnetid)" \
                            appgwip="$(appgwip)" \
                            managedClusters_aks_cluster_name="$(managedClusters_aks_cluster_name)" \
                            appgwumi="$(appgwumi)" \
                            sslcertname="$(sslcertname)"
        - task: AzureCLI@2
          displayName: "deploy infrastructure"
          inputs:
            azureSubscription: 'aks-sc1'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
                          az deployment group create \
                          --resource-group "mmt-aks" \
                          --mode Incremental \
                          --template-file "$(System.DefaultWorkingDirectory)/InfraProvisioning/main.bicep" \
                          --parameters virtualNetworkName="$(virtualNetworkName)" \
                                      AkssubnetName="$(AkssubnetName)" \
                                      AppgwsubnetName="$(AppgwsubnetName)" \
                                      PlesubnetName="$(PlesubnetName)" \
                                      windowsAdminPassword="$(windowsAdminPassword)" \
                                      acrName="$(acrName)" \
                                      frontendfqdn="$(frontendfqdn)" \
                                      applicationGateways_appgw_name="$(appGatewayName)" \
                                      appgwkeyvault="$(appgwkeyvault)" \
                                      storageAccountName="$(storageAccountName)" \
                                      umiName="$(umiName)" \
                                      Plesubnetid="$(plesubnetid)" \
                                      appgwSubnetID="$(appgwsubnetid)" \
                                      appgwip="$(appgwip)" \
                                      managedClusters_aks_cluster_name="$(managedClusters_aks_cluster_name)" \
                                      appgwumi="$(appgwumi)" \
                                      sslcertname="$(sslcertname)"


                                      
                            
                          